name: Fotof
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8333748
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#3b3b3b'
    - '#7a7a7a'
    - '#9f9f9f'
  brandStrength: 0.7775404
  lightness: 0.8164037
  saturation: 0.4375
  rhythmicContrast: 0.9756836
purpose: []
